homePage:
    pattern: /
    defaults: { _controller: CoreBundle:Default:index }

product:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"