product_add:
    pattern: /product/add
    defaults: { _controller: CoreBundle:Product:index}
    options:
            expose: true

product_list_angular:
    pattern: /project/project-list
    defaults: { _controller: CoreBundle:Product:productList}
    options:
            expose: true
